/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                "background": "#131313",
                "on-tertiary": "#003351",
                "on-secondary": "#002e6a",
                "tertiary-container": "#00a2f4",
                "secondary-fixed": "#d8e2ff",
                "on-primary": "#552100",
                "surface-container-lowest": "#0e0e0e",
                "surface-container-low": "#1c1b1b",
                "on-secondary-fixed-variant": "#004395",
                "surface-container-high": "#2a2a2a",
                "primary-fixed-dim": "#ffb690",
                "on-tertiary-container": "#003554",
                "tertiary": "#93ccff",
                "primary-fixed": "#ffdbca",
                "secondary-container": "#0566d9",
                "surface-dim": "#131313",
                "on-background": "#e5e2e1",
                "secondary": "#adc6ff",
                "on-tertiary-fixed-variant": "#004b74",
                "primary": "#ffb690",
                "on-surface": "#e5e2e1",
                "surface-bright": "#3a3939",
                "surface": "#131313",
                "surface-container-highest": "#353534",
                "on-secondary-container": "#e6ecff",
                "inverse-on-surface": "#313030",
                "error-container": "#93000a",
                "on-primary-container": "#582200",
                "tertiary-fixed-dim": "#93ccff",
                "secondary-fixed-dim": "#adc6ff",
                "on-surface-variant": "#e0c0b1",
                "on-primary-fixed": "#341100",
                "on-secondary-fixed": "#001a42",
                "tertiary-fixed": "#cde5ff",
                "surface-variant": "#353534",
                "on-tertiary-fixed": "#001d32",
                "inverse-primary": "#9d4300",
                "error": "#ffb4ab",
                "on-error": "#690005",
                "surface-container": "#201f1f",
                "surface-tint": "#ffb690",
                "on-primary-fixed-variant": "#783200",
                "outline": "#a78b7d",
                "inverse-surface": "#e5e2e1",
                "on-error-container": "#ffdad6",
                "primary-container": "#f97316",
                "outline-variant": "#584237"
            },
            fontFamily: {
                "sans": ["Inter", "sans-serif"],
                "headline": ["Plus Jakarta Sans", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
    plugins: [],
}
